version: '3.5'

services:
  ###
  # applications
  ###

  core_app:
    build:
      context: ../
      dockerfile: ./build/package/core/Dockerfile.development
    container_name: aether_core_app
    env_file:
      - ../.config/.env.core
    image: aether/core-web
    networks:
      - aether
    ports:
      - "${CORE_APP_PORT:-3000}:${CORE_APP_PORT:-3000}"
    volumes:
      - ../.files:/usr/app/.files:cached
      - ../.temp:/usr/app/.temp:cached
      - ../cmd:/usr/app/cmd:cached
      - ../internal:/usr/app/internal:cached

  web_app:
    build:
      context: ../
      dockerfile: ./build/package/web/Dockerfile.development
    container_name: aether_web_app
    env_file:
      - ../.config/.env.web
    image: aether/web-app
    networks:
      - aether
    ports:
      - "${WEB_APP_PORT:-8080}:${WEB_APP_PORT:-8080}"
    volumes:
      - ../app:/usr/app/app:cached
      - ../next.config.mjs:/usr/app/next.config.mjs:cached
      - ../package.json:/usr/app/package.json:cached
      - ../public:/usr/app/public:cached
      - ../tsconfig.json:/usr/app/tsconfig.json:cached

networks:
  aether:
    name: aether
