name: "Release"

on:
  push:
    branches:
      - main

jobs:
  ##
  # install
  ##

  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-yarn-dependencies

  ##
  # release
  ##

  release:
    name: "Release"
    needs: [install]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-yarn-dependencies
      - name: "🔖 Release"
        env:
          # appears on the release commits
          GIT_AUTHOR_NAME: kieranroneill
          GIT_AUTHOR_EMAIL: hello@kieranoneill.com
          GIT_COMMITTER_NAME: kieranroneill
          GIT_COMMITTER_EMAIL: hello@kieranoneill.com
          # used to push the release commit and create the tags
          GITHUB_TOKEN: ${{ secrets.READ_AND_WRITE_REPOS_TOKEN }}
        run: yarn semantic-release
